"""Schematic campus coordinates; row 0 is north, column 0 is west.

This is a diagram of the prototype graph, not a surveyed walking map.
Both the Arduino's default map and serial step masks come from this file.
"""
from graph import GRAPH

ROWS, COLUMNS = 8, 12
LOCATION_ORDER = (
    "WMC", "Library", "SUB", "MBC", "AQ", "Shrum Chemistry",
    "Shrum Physics", "Shrum Biology", "South Sciences", "ASB", "TASC1", "TASC2",
)
NODE_PIXELS = {
    "WMC": (1, 0), "WMC_EAST": (1, 1), "LIBRARY_WEST": (1, 2),
    "Library": (1, 3), "CONVOCATION_WEST": (2, 2),
    "CONVOCATION_CENTRE": (2, 3), "MBC": (3, 2), "SUB": (3, 4),
    "AQ_WEST": (2, 4), "AQ": (2, 5), "AQ_SOUTH": (3, 5),
    "SHRUM_NORTH": (4, 5), "Shrum Chemistry": (5, 4),
    "Shrum Physics": (5, 6), "Shrum Biology": (5, 8),
    "SHRUM_SOUTH": (6, 5), "South Sciences": (7, 4),
    "ASB_WEST": (5, 9), "ASB": (5, 10), "TASC_JUNCTION": (6, 10),
    "TASC1": (7, 11), "TASC2": (7, 9),
}


def edge_pixels(start, end):
    """Rasterize an undirected graph edge consistently in both directions."""
    if end not in GRAPH[start]:
        raise ValueError(f"No graph edge from {start} to {end}")
    (r0, c0), (r1, c1) = sorted((NODE_PIXELS[start], NODE_PIXELS[end]))
    steps = max(abs(r1 - r0), abs(c1 - c0))
    return {(round(r0 + (r1 - r0) * i / steps),
             round(c0 + (c1 - c0) * i / steps)) for i in range(steps + 1)}


def pack_pixels(pixels):
    """96 row-major bits, most significant bit first, as 24 hex characters."""
    data = bytearray(12)
    for row, column in pixels:
        if not (0 <= row < ROWS and 0 <= column < COLUMNS):
            raise ValueError("Pixel outside 8 x 12 display")
        index = row * COLUMNS + column
        data[index // 8] |= 1 << (7 - index % 8)
    return data.hex().upper()


def unpack_pixels(mask):
    if len(mask) != 24:
        raise ValueError("Matrix mask must contain 24 hex characters")
    data = bytes.fromhex(mask)
    return {(i // COLUMNS, i % COLUMNS) for i in range(96)
            if data[i // 8] & (1 << (7 - i % 8))}


def mask_for_path(path):
    pixels = {NODE_PIXELS[node] for node in path}
    for start, end in zip(path, path[1:]):
        pixels.update(edge_pixels(start, end))
    return pack_pixels(pixels)


BASE_PIXELS = set(NODE_PIXELS.values())
for _start, _neighbors in GRAPH.items():
    for _end in _neighbors:
        BASE_PIXELS.update(edge_pixels(_start, _end))
BASE_MASK = pack_pixels(BASE_PIXELS)


def write_arduino_header(path):
    """Regenerate after editing coordinates; upload the sketch again."""
    data = bytes.fromhex(BASE_MASK)
    rows = ", ".join(str(NODE_PIXELS[n][0]) for n in LOCATION_ORDER)
    columns = ", ".join(str(NODE_PIXELS[n][1]) for n in LOCATION_ORDER)
    path.write_text(
        "// Generated by python/matrix_map.py; edit coordinates there.\n"
        "#pragma once\n"
        "const uint8_t DEFAULT_MAP[12] = {" +
        ", ".join(f"0x{b:02X}" for b in data) + "};\n"
        f"const uint8_t LOCATION_ROWS[12] = {{{rows}}};\n"
        f"const uint8_t LOCATION_COLUMNS[12] = {{{columns}}};\n",
        encoding="ascii",
    )


if __name__ == "__main__":
    from pathlib import Path
    write_arduino_header(Path(__file__).resolve().parents[1] /
                         "arduino/navigator/campus_map.h")
