// Generated by python/matrix_map.py; edit coordinates there.
#pragma once
const uint8_t DEFAULT_MAP[12] = {0x00, 0x0F, 0x00, 0x3C, 0x02, 0xC0, 0x04, 0x00, 0xFE, 0x07, 0x20, 0xC7};
const uint8_t LOCATION_ROWS[12] = {1, 1, 3, 3, 2, 5, 5, 5, 7, 5, 7, 7};
const uint8_t LOCATION_COLUMNS[12] = {0, 3, 4, 2, 5, 4, 6, 8, 4, 10, 11, 9};
